version: '3'

services:
  adminer:
    image: adminer
    ports: ["9080:8080"]
    restart: always
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - 5432:5432
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
